ref_genome: arcgaz

query_genomes:
  - acijub
  - ailmel
  - arcgaz
  - calurs
  - canlup
  - carcar
  - chrbra
  - crocro
  - cryfer
  - eirbar
  - enhlut
  - eumjub
  - felcat
  - felcha
  - felnig
  - halgry
  - helpar
  - hyahya
  - leogeo
  - lepwed
  - loncan
  - lutlut
  - lycpic
  - lyncan
  - lynpar
  - lynruf
  - marzib
  - melmel
  - melcap
  - mirang
  - mirleo
  - munmun
  - muserm
  - musnig
  - musniv
  - musput
  - neosch
  - nycpro
  - odoros
  - panleo
  - panonc
  - panpar
  - pantig
  - panunc
  - parher
  - phovit
  - potfla
  - priben
  - priiri
  - priviv
  - prolot
  - ptebra
  - pumcon
  - pumyag
  - speven
  - spigra
  - sursur
  - taxtax
  - treorn
  - ursame
  - ursarc
  - ursmar
  - ursthi
  - vulfer
  - vullag
  - vulvul
  - zalcal
